FROM nginxinc/nginx-unprivileged:1.27-alpine

USER root
COPY platform/app/dist /usr/share/nginx/html
COPY nginx.patient.conf /etc/nginx/conf.d/default.conf
RUN chown -R nginx:nginx /usr/share/nginx/html

USER nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
